version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: chat_dr_bread
    restart: always
    ports:
      - "5439:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: J7u!xE9r%pLz#4Wq
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
